{"name": "expected exception", "status": "passed", "parameters": [{"name": "first_para", "value": "2"}, {"name": "second_para", "value": "0"}, {"name": "expected", "value": "<class 'ZeroDivisionError'>"}], "start": 1577542918604, "stop": 1577542918605, "uuid": "20621e2f-6e48-4a5a-8241-3719efee9673", "historyId": "f3011a70bc613317025b0bcaeec189c4", "testCaseId": "2ec7f2475aae25c72397e4d9deaec871", "fullName": "unit.test_div#test_div_error", "labels": [{"name": "tag", "value": "exception"}, {"name": "parentSuite", "value": "unit"}, {"name": "suite", "value": "test_div"}, {"name": "host", "value": "WIN-1GF9INK28GB"}, {"name": "thread", "value": "3304-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "unit.test_div"}]}